name: Build and Deploy

on:
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v2.3.6 # Match your local Deno version

            - name: Verify Deno installation
              run: deno --version

            - name: Cache Deno dependencies
              uses: actions/cache@v3
              with:
                  path: |
                      ~/.deno
                      ~/.cache/deno
                  key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
                  restore-keys: |
                      ${{ runner.os }}-deno-

            - name: Install dependencies
              run: deno install --reload

            - name: Lint code
              run: deno task lint

            # - name: Format check
            #   run: deno task fmt --check

            - name: Build project
              run: deno task build

            - name: Run tests (if any)
              run: deno task test
              continue-on-error: true # Allow failure if no tests exist
